### ISSUE TITLE
When is the planned release date/timeline for OpenC3 Version 5.0.9?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/openc3#108]
Hello,

My team is anxiously awaiting the next OpenC3 version. Do you have a rough estimate for when to expect that?

Thanks,

Dakota

**Comment by ryanmelt** [comment]
Hi Dakota,
We are there on the development front.  I just want to get more testing in on the local mode pull request so that that change makes it into the release.   Should be ready by the end of the day tomorrow (Aug 31st).

**Comment by GTI-Dakota** [comment]
Awesome, thanks for the update!

**Comment by ryanmelt** [comment]
Hey Dakota - 
Just an update.  This is slipping to tomorrow so we can get all the tests green again.
Local mode itself is fully tested though and I'm excited to get that released.  :)

**Comment by ryanmelt** [comment]
https://github.com/OpenC3/openc3/releases/tag/v5.0.9

**Comment by ryanmelt** [comment]
Enterprise should be released this afternoon
