### ISSUE TITLE
OpenC3 Scope Spinup/Spindown

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/openc3#109]
Hello,

While reviewing your documentation for OpenC3 Enterprise, it appears to me that the Scopes in COSMOS are not simultaneously running environments, and only one can be active at a time. Is this the only way to utilize the Scopes or is there a way to run multiple scopes in tandem? If there is no currently any functionality for that, are there any plans to implement it?

Thanks,

Dakota

**Comment by ryanmelt** [comment]
Scopes are all running at the same time (all the microservices are running simultaneously), but the user interface is locked to a selected single scope. (So you are interacting with only one scope at a time).

Your question did just make me think of a potential unintended implementation side effect though.  We store the current selected scope in browser localStorage, which may have unintended consequences when changing it across browser tabs.   The intention is that different tabs could be interacting with different scopes - But that may be currently broken - I will investigate.

**Comment by GTI-Dakota** [comment]
Ryan, thanks for the information. So I should be able to run a "backend" server with multiple scopes, sans-web interacion, without issues? The "unloading of gems" from the docs, as I understand, is on a browser-based session viewing?

**Comment by ryanmelt** [comment]
Yes you should be able to run multiple scopes in the backend without issues.

Can you point me to where you are seeing "unloading of gems"?

Tools and gems are available to all scopes, regardless to which scope they are installed from.

Scopes contain differentiated: targets (includes all target attributes like commands, telemetry, screens, procedures), interfaces, routers, and microservices.
