### ISSUE TITLE
in Telemetry viewer, support ERB code when pasting or writing a new screen definition using `new screen'

### ISSUE THREAD

**Issue by jurgensymynck** [OpenC3/openc3#112]
**Is your feature request related to a problem? Please describe.**
It appears that copy-pasting ERB-laden screen definition files from COSMOS 4.X to Openc3 doesn't work as expected:

`Error: Unknown widget: <%Widget.
![image](https://user-images.githubusercontent.com/837194/187496582-bb56a652-2582-4241-8564-eb0ac5429659.png)

**Describe the solution you'd like**
The <% (0..7).each do |i| %> <% end %> should work in the screen definition editor.

**Additional context**
This issue is linked with [this issue](https://github.com/OpenC3/openc3/issues/111) where I fail to test how to use the above code in telemetry screens.
I noticed that when opening the  provided [INST target `grounds.txt` telemetry screen](https://github.com/OpenC3/openc3/blob/master/openc3-init/plugins/packages/openc3-demo/targets/INST/screens/ground.txt), the code is already  expanded 
So, its very well possible this is not supported by design, but at the time I cannot verify this due to the mentioned issue...

greetings, Jurgen

**Comment by jmthomas** [comment]
The ERB code is only parsed when the plugin is installed, thus you can't copy and paste ERB code into a new screen definition.
