### ISSUE TITLE
Comments in telemetry screen configuration files do not prevent ERB code from being evaluated while installing plugins

### ISSUE THREAD

**Issue by jurgensymynck** [OpenC3/openc3#117]
**Describe the bug**
Comments in telemetry screen configuration files do not prevent ERB code from being evaluated while installing plugins.

**To Reproduce**
- with a code editor, make a telemetry viewer config file that contains following line:
`  # <%= render "_NONEXISTING_FILE_rate_tlm_and_sample.txt" %>`
- build plugin containing this file
- upload or replace existing plugin
- plugin installing crashes while trying to evaluate the commented ERB code
`Stderr:
Error installing plugin: DEFAULT: openc3-lorerobot-0.95.0.pre.alpha.20.20220831112336.gem: RuntimeError : ERB error parsing: /tmp/d20220831-200-yc5ozk/gem/targets/LOREROBOT/screens/calibrate.txt: RuntimeError : ERB error parsing: /tmp/d20220831-200-yc5ozk/gem/targets/LOREROBOT/screens/_NONEXISTING_FILE_rate_tlm_and_sample.txt: ENOENT : No such file or directory @ rb_sysopen - /tmp/d20220831-200-yc5ozk/gem/targets/LOREROBOT/screens/_NONEXISTING_FILE_rate_tlm_and_sample.txt`

**Expected behavior**
comments should disable all following ERB code

**Screenshots**
![image](https://user-images.githubusercontent.com/837194/187668934-dc832328-9562-440c-bd18-d2ceb321871a.png)
![image](https://user-images.githubusercontent.com/837194/187669288-a3df735a-c4ab-4062-9e7e-af21ad8ce5a0.png)

**Environment (please complete the following information):**

- Windows 10
- OpenC3 5.0.8
- Browser: Chrome 104.0.5112.102 (Officiële build) (64-bits)

**Comment by ryanmelt** [comment]
You have to comment out the ERB code itself.   Building the content of comments with ERB is completely valid.
```<%#= render ... %>```

https://stackoverflow.com/questions/2774841/best-way-to-add-comments-in-erb
