### ISSUE TITLE
Critical notifications counter is limited to 100 without indication that more have occured

### ISSUE THREAD

**Issue by jurgensymynck** [OpenC3/openc3#118]
**Describe the bug**
Critical notifications counter is limited to 100 without indication that more have occured

**Expected behavior**
- increase limit to 9999 or more
- add indicator to show that more have occurred, like `100+` or ` >100`

**Screenshots**
![image](https://user-images.githubusercontent.com/837194/187669956-dec230d0-2f2e-4ad2-8149-36d3687d8c03.png)

**Environment (please complete the following information):**

- Windows 10
- OpenC3 5.0.8
- Browser: Chrome 104.0.5112.102 (Officiële build) (64-bits)

**Comment by jmthomas** [comment]
This is a good enhancement and our Demo exercises it quite rapidly. Thanks for the suggestion!
