### ISSUE TITLE
XTCE parameters

### ISSUE THREAD

**Issue by AstreeDeshayes** [OpenC3/openc3#12]
Hello,

I want to use an xtce file for command and telemetry but some of its parameters are not supported by OpenC3. Would it be possible to add these parameters so that they are supported by OpenC3 please?

- Boolean
- Crc
- Absolute time parameter

Thanks,
Astrée Deshayes

**Comment by jmthomas** [comment]
XTCE support isn't high on our todo list at this point. Do you have specific examples of these fields and how to use them?

**Comment by ryanmelt** [comment]
If you could provide a representative file that you would like to see work, that would be very helpful.

**Comment by AstreeDeshayes** [comment]
Yes of course, here it is : 
[MDB.zip](https://github.com/OpenC3/openc3/files/9178797/MDB.zip)
