### ISSUE TITLE
All Time Stamps on custom interfaces not updating

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/openc3#139]
Hello,

We at GTI have noticed that packets coming from custom interfaces/protocols no longer have their timestamps updated. This affects the ability to utilize the tlm grapher, and keep track of when the last packet receive time was.

Thanks,

Dakota

**Comment by ryanmelt** [comment]
Custom interfaces aren't different than the bundled interfaces, so it's probably something wrong in the custom interface code.  In particular, you must clear received_time on the packet if you are reusing a packet object before returning from read.

If that isn't the issue, please post the code here, or email us at support@openc3.com

**Comment by GTI-Dakota** [comment]
Roger. We have cleared/updated the receive time as you specified, and no further problems have been observed regarding this issue. Thanks!
