### ISSUE TITLE
Open File Dialog does not retain uploaded file name

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/openc3#140]
Hello, 

When using the open_file_dialog api in the script runner, the name of the uploaded file is not preserved, as the file object created by the upload is a temp file. This results in a user needing to manually enter the filename via a prompt or otherwise AFTER the file upload. Is there a way to update this so the original filename can be referenced from the return?

Thanks,

Dakota

**Comment by ryanmelt** [comment]
It would be good to have a way to know the original file name.  That's how rails file uploads work too.
