### ISSUE TITLE
put_target_file freezes Script Runner

### ISSUE THREAD

**Issue by bryan-gti** [OpenC3/openc3#173]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
With or without Local Mode Enabled, put_target_file causes SR to hang.

Observations:
- Clicking the "Go" button cause the script to continue
- When local mode is enabled, file is written to the local file system
- File is never written to minio

**To Reproduce**
Run 'openc3-demo/targets/INST/procedures/target_file.rb'

**Comment by ryanmelt** [comment]
Thanks - Will get this fixed in the release today.
