### ISSUE TITLE
connect_interface does not send parameters

### ISSUE THREAD

**Issue by bradenvirdellgenevatech** [OpenC3/openc3#177]
Reviewing the documentation it says:
connect_interface("<Interface Name>", <Interface Parameters (optional)>)
Interface parameters referring to the initialization of an interface. 

It appears that the ability to send parameters has not been implemented.

I would like the ability to send these parameters to change the configuration of an interface instance through the script runner upon connecting the interface. This would allow me to reduce the number of interfaces I need.

**Comment by jmthomas** [comment]
You're right that this doesn't appear to be implemented.
