### ISSUE TITLE
Ad hoc commanding from outside of the script runner

### ISSUE THREAD

**Issue by Ne0wan** [OpenC3/openc3#191]
I am trying to execute commands in response to specific telemetry item values that are received. I am currently trying to use the PROCESSOR modifier in my telemetry items to trigger some business logic that could lead to a commanding event, but I haven't been successful in getting commanding to work from outside of the script runner. I have also considering the microservice feature to host host some logic, but I think there is the same issue with sending commands. Ideally, we would like to be able to have access to the scheduling API so we could perform ad hoc commands and/or schedule commands. 

So a couple questions.
Is there a better way to approach what I am trying to achieve here and are there any examples or tips you could provide to get access to sending commands outside of the script runner?

Thanks,
Billy

**Comment by ryanmelt** [comment]
PROCESSORS aren't meant to have side effects (like sending commands), because they might end up running multiple times between different microservices.

I would recommend using a custom microservice.  You can send commands from microservices by adding "include Api" to the class that needs to send commands.

**Comment by jhayes-apl** [comment]
I had a similar question.  I ended up using a custom protocol rather than a PROCESSOR.  See:
https://github.com/OpenC3/openc3/issues/95

**Comment by Ne0wan** [comment]
> I had a similar question. I ended up using a custom protocol rather than a PROCESSOR. See: #95

Much appreciated, I will definitely pull on that thread.
