### ISSUE TITLE
Received count on inject_tlm

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/openc3#196]
When using inject_tlm. Encountered received count stuck at 1 based on the tlm_api line 140. 

Instead of:
 packet.received_count += 1

Suggest maybe:
  begin
    packet.received_count = CvtModel.get_item(target_name, packet_name, "RECEIVED_COUNT", type: type.intern, scope: scope) + 1
  rescue Exception => err
    packet.received_count = 1
  end

This is due to the fact that if the packet is generated with a received count of 0 so 0+=1 will always be 1.

**Comment by jmthomas** [comment]
Related to #183
