### ISSUE TITLE
InvalidTimezoneIdentifer error

### ISSUE THREAD

**Issue by apogeecmb** [OpenC3/openc3#200]
I am getting a fatal error over and over again in CmdTlmServer, although I'm still able to flow commands and telemetry through OpenC3.  Appears to be related to the timezone definition.  I am running OpenC3 on Ubuntu Linux.

Microservice DEFAULT__REDUCER__TEST dying from exception InvalidTimezoneIdentifier : uninitialized constant TZInfo::Data::Definitions::America::Belem split_identifier.each {|part| m = m.const_get(part) } ^^^^^^^^^^ (loading America/Belem) /usr/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.5/lib/tzinfo/data_sources/ruby_data_source.rb:103:in `rescue in load_timezone_info' /usr/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.5/lib/tzinfo/data_sources/ruby_data_source.rb:96:in `load_timezone_info' /usr/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.5/lib/tzinfo/data_source.rb:195:in `get_timezone_info' /usr/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.5/lib/tzinfo/timezone.rb:128:in `get' /usr/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.5/lib/tzinfo/timezone_proxy.rb:88:in `real_timezone' /usr/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.5/lib/tzinfo/timezone_proxy.rb:41:in `periods_for_local' /usr/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.5/lib/tzinfo/timezone.rb:497:in `period_for_local' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/zones.rb:230:in `block in determine_local_tzones' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/zones.rb:229:in `select' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/zones.rb:229:in `determine_local_tzones' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/zones.rb:76:in `determine_local_tzone' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/zone.rb:10:in `get_tzone' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/time.rb:32:in `get_tzone' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/time.rb:80:in `initialize' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/make.rb:17:in `new' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/make.rb:17:in `now' /usr/lib/ruby/gems/3.1.0/gems/et-orbi-1.2.7/lib/et-orbi/time.rb:22:in `now' /usr/lib/ruby/gems/3.1.0/gems/rufus-scheduler-3.8.2/lib/rufus/scheduler.rb:631:in `start' /usr/lib/ruby/gems/3.1.0/gems/rufus-scheduler-3.8.2/lib/rufus/scheduler.rb:98:in `initialize' reducer_microservice.rb:52:in `new' reducer_microservice.rb:52:in `run' /usr/lib/ruby/gems/3.1.0/gems/openc3-5.0.10/lib/openc3/microservices/microservice.rb:47:in `run' reducer_microservice.rb:313:in `<main>'

**Comment by apogeecmb** [comment]
No, I'm actually in the US central time zone.  Though all the times in OpenC3 show up as UTC.  Is there a time zone setting that should be set somewhere in the OpenC3 configuration?

**Comment by jmthomas** [comment]
We don't have any local timezone settings but your OS does. Belem is in Brazil so while that _might_ be the same as CST you should probably fix your Ubuntu timezone. Not sure why you would be seeing the error though.

**Comment by apogeecmb** [comment]
Belem is not the same timezone, and my Ubuntu timezone settings appear to be accurate per timedatectl:

Time zone:  America/Chicago (CDT, -0500)

Like I said, the error does not appear to be affecting functionality other than mucking up the log messages in the CmdTlmServer.  I can just ignore it I suppose.

**Comment by ryanmelt** [comment]
Data reduction is crashing so you won't have reduced data.  We'll dig in, thanks for the additional info.

**Comment by apogeecmb** [comment]
I was having some stability issues with my virtual machine, so I created a new one.  After creating the new VM, this error is no longer occurring.  I'm guessing it was an unrelated OS data corruption issue.  Apologies for the confusion.
