### ISSUE TITLE
Where are Telemetry Grapher configurations stored?

### ISSUE THREAD

**Issue by jhayes-apl** [OpenC3/openc3#206]
I used Save Configuration under Telemetry Grapher; the configurations name is mag566_all.  Where is this saved?  I have searched through minio.  I even searched through the container hierarchy (~/.local/share/containers) and I cannot find it.  I have two instances of COSMOS on distinct laptops and want to keep them consistent.  I am using COSMOS 5.0.4 on Linux.

**Comment by ryanmelt** [comment]
Dup of #187.  Currently this information is only stored in Redis.  Our next update to local mode will provide a way to configuration manage these settings and move them between computers.
