### ISSUE TITLE
wait*() raises NoMethodError if no packets of the given type has ever arrived

### ISSUE THREAD

**Issue by martinerikwerner-aac** [OpenC3/openc3#215]
**Describe the bug**
If the `wait*()` functions are called with a packet check as part of the expression, and that packet has never been seen yet, the script aborts with the following type of error:

```
2022/10/15 12:53:43.945 (SCRIPTRUNNER): Script stopped: 2022_10_15_14_53_11_247_temp.rb
2022/10/15 12:53:43.940 (SCRIPTRUNNER): Script config/DEFAULT/targets/__TEMP__/2022_10_15_14_53_11_247_temp.rb received command: "stop"
2022/10/15 12:53:39.318 (2022_10_15_14_53_11_247_temp.rb:1): __TEMP__/2022_10_15_14_53_11_247_temp.rb:1:in `block (2 levels) in run_text'
2022/10/15 12:53:39.317 (2022_10_15_14_53_11_247_temp.rb:1): NoMethodError : undefined method `+' for nil:NilClass

                                                         ">= #{initial_count + num_packets}",
                                                                             ^
2022/10/15 12:53:39.173 (SCRIPTRUNNER): Starting script: 2022_10_15_14_53_11_247_temp.rb
2022/10/15 12:53:39.142 (SCRIPTRUNNER): Script config/DEFAULT/targets/__TEMP__/2022_10_15_14_53_11_247_temp.rb spawned in 1.018251421 seconds <ruby 3.1.2>
```

This seems to be due to the following code in

https://github.com/OpenC3/openc3/blob/834742cff3d2ddc11b49257464df3fe815784375/openc3/lib/openc3/script/api_shared.rb#L557-L575

where I assume that `tlm()` returns `nil` if no packets have ever been seen, and thus results in the `initial_count + num_packets` expression failing.

When using other wait commands than `wait_check_packet()` the error is similar but slightly different

```
(eval):1:in `_openc3_script_wait_implementation'
in `block (2 levels) in run_text'
NoMethodError : undefined method `>' for nil:NilClass
```

which I assume is due to the following code:

https://github.com/OpenC3/openc3/blob/834742cff3d2ddc11b49257464df3fe815784375/openc3/lib/openc3/script/api_shared.rb#L696-L707

where again, the `tlm()` call return `nil` which makes the expression from

https://github.com/OpenC3/openc3/blob/834742cff3d2ddc11b49257464df3fe815784375/openc3/lib/openc3/script/api_shared.rb#L744

fail to evaluate at

https://github.com/OpenC3/openc3/blob/834742cff3d2ddc11b49257464df3fe815784375/openc3/lib/openc3/script/api_shared.rb#L707

**To Reproduce**

1. Make sure that a target exists with a telemetry packet which has never been received.
2. Use script runner to create a new script with
    ```
    wait_check_packet("TEST_TARGET", "TEST_TLM", 10)
    ```
3. Run the script.

**Expected behavior**

I would expect the script runner to do one of the following:
* Wait for 10 seconds and then raise a timeout exception.
* (Wait some time and exit normally if the packet was actually received)

**Environment**

- OS: Debian 11
- OpenC3 Version 5.0.11
- Browser
  -- [x] Mozilla Firefox

**Comment by jmthomas** [comment]
@martinerikwerner-aac thank you for such a detailed write-up! This fix will be in the next release (probably 5.1.0)
