### ISSUE TITLE
Connecting to external database

### ISSUE THREAD

**Issue by wiatrp** [OpenC3/openc3#218]
I need to connect to a remote PostgreSQL database and am using the [ruby-pg gem](https://github.com/ged/ruby-pg). Is there a recommended way to do this in OpenC3? In a typical rails app I can add the database connection params in the `config/database.yaml` file but it doesn't seem like the OpenC3 APIs recognize that file.

For now I've decided to go the same route as the `Store` class and just create my own for the `PG` connection which seems to be working nicely.

**Comment by ryanmelt** [comment]
Sounds like you are doing right.  I would create a new class, and pass in the credentials with environment variables.
