### ISSUE TITLE
Creating OpenC3 Custom Protocol/Interface

### ISSUE THREAD

**Issue by DavidWathen** [OpenC3/openc3#222]
I'm looking into how I can best implement logic for a new protocol/interface that will be able to parse the types of packets I'm working with. The packet type I'm working with will be a sync pattern, length based encapsulated packet, with a CRC, that has a body containing multiple complete CCSDS packets. 
I've spent time looking closer at the OpenC3 source and in particular the protocol and interface classes. From my understanding it looks like I will need to create my own interface class that inherits from the TcpipServerInterface so that I can override the read method to return each of the CCSDS packets that are discovered in the body of the encapsulated packet. This way the handle_packet() call in the interface_thread/interface_microservice classes, which identifies the packet based on our configuration, is called for each CCSDS packet that is discovered. 

Does my approach make sense? 

Is this the best approach to take? 

Any hints on what needs to be done to accomplish this?

Thanks,

David

**Comment by jmthomas** [comment]
It sounds like you can use our existing interface with an existing LENGTH protocol and then add another LENGTH protocol to pull apart the inner CCSDS packets. [Protocol](https://openc3.com/docs/v5/protocols) documentation is definitely the place to start. I also wrote an old [blog post](https://ballaerospace.github.io/cosmos-website/news/2019/06/05/protocols/) about this that might be helpful.
