### ISSUE TITLE
Rename "Download" button to "Upload" in plugin admin page

### ISSUE THREAD

**Issue by erdnaxe** [OpenC3/openc3#226]
**Describe the bug**
In `ADMIN > PLUGINS`, the `DOWNLOAD` button is used to send a gem to the OpenC3 server.
The terminology is not intuitive for the user, usually client->server is called uploading in web software.

**To Reproduce**

1. Click 'ADMIN'
2. Click on 'PLUGINS'
3. Observe the dark blue bar containing the "DOWNLOAD" button.

**Expected behavior**
1. Click 'ADMIN'
2. Click on 'PLUGINS'
3. Observe the dark blue bar containing the "UPLOAD" button.

**Environment (please complete the following information):**

- OS: NixOS 22.05, using openc3.sh with Docker.
- OpenC3 Version 5.0.11
- Browsers:
  - Google Chrome 106.0.5249
  - Mozilla Firefox 106.0.1

**Comment by jmthomas** [comment]
This button is actually intended to go out to Rubygems and download OpenC3/COSMOS gems. This isn't a fully implemented feature so I'm going to remove it for now as it is obviously confusing.
