### ISSUE TITLE
View "Command Sender" logs in a telemetry screen?

### ISSUE THREAD

**Issue by KodiakLiDAR** [OpenC3/openc3#230]
Hello OpenC3 Team,

Is there a way to view the "Command Sender" logs or "Command and Telemetry Server" logs in a separate window or telemetry screen?

Bonus points if there is a way to increase the list length so that I can scroll all the way back to the first log message (Within the Command Sender or CTS tools, there is a limit to the log list length, preventing older log messages from being seen).

Thank you very much for any and all guidance.

Kindly,
Kodiak

**Comment by jmthomas** [comment]
We are tracking this in #144

**Comment by KodiakLiDAR** [comment]
thank you @jmthomas. I'll watch for any advancements on this feature request while I continue to work on a solution. I'll you keep you posted with my progress.
