### ISSUE TITLE
Packet 'EXAMPLE STATUS' does not exist

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/openc3#56]
The CVT contains no data for the EXAMPLE STATUS packet in the demo by default, which is a causing a 500 error, packet does not exist in Packet Viewer

**Comment by jmthomas** [comment]
@ryanmelt I simply see a blank page with all the values set to `null`. I do not get the 500 error. Can you reproduce this on master?

**Comment by ryanmelt** [comment]
Figured this out.  This is happening because the Current Value Table (CVT) is stored in the Ephemeral Redis container.   As soon as that container restarts for any reason, the packet full of nil values is lost and no longer exists.  @jmthomas

**Comment by ryanmelt** [comment]
Can be recreated immediately with: docker restart openc3-openc3-redis-ephemeral-1
