### ISSUE TITLE
Differences between COSMOS and OpenC3

### ISSUE THREAD

**Issue by keck-in-space** [OpenC3/openc3#72]
Hello,

I am curious what option I should choose between OpenC3 and COSMOS v5. Is there a list of differences anywhere?

Thank you.

**Comment by ryanmelt** [comment]
OpenC3 is the continuation of COSMOS 5, by its creators.   We've forked COSMOS and are continuing it full-time as a new company, OpenC3.   

The current differences are the changes we've put into the 3 releases we've done so far.   

You can see the release notes here: https://github.com/OpenC3/openc3/releases

Also, we've just finished the first version of OpenC3 Enterprise Edition - a paid product that adds multi-user support, RBAC, and scopes, with a lot more to come.

**Comment by keck-in-space** [comment]
Thanks Ryan. Will COSMOS v5 be developed further, or only OpenC3?

**Comment by jmthomas** [comment]
The 2 authors of COSMOS are now at OpenC3 and we can only speak to what we're doing with OpenC3. Please contact us at support@openc3.com and perhaps we can setup a call to discuss further.

**Comment by keck-in-space** [comment]
Got it. Thanks so much.
