### ISSUE TITLE
JS tlm_raw() function in screen buttons

### ISSUE THREAD

**Issue by vidfare** [OpenC3/openc3#86]
I can't find any JavaScript tlm_raw() function to use in screen files in OpenC3/COSMOS5. In COSMOS4 there was a tlm_raw() Ruby function. Sometimes I need the numeric value. 
Is there any way to get the raw TLM value? Or will you add a tlm_raw() function for JS?

**Comment by jmthomas** [comment]
This is indeed missing. We will add this in the next release. Thanks for bringing this to our attention!

**Comment by vidfare** [comment]
Thanks for adding the function!

**Comment by vidfare** [comment]
I tried the existing api.cmd() JS function defined in openc3-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js and it returns a [Promise ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) object, not the TLM value.
I might be wrong, but it looks like a function declared with async always returns a Promise object regardless what you have in your return statement.
You are able to get the TLM value inside the api.cmd() function, but you can't return it. I looked around and it looks quite complicated to get a resulting value out from an async function.
The other async declared functions probably also returns a Promise object.

**Comment by vidfare** [comment]
I found a way to get the TLM value.

I made my own tlm_raw() function which is very similar to the existing tlm() function:

```
  async tlm_raw(target_name, packet_name, item_name) {
    const data = await this.exec('tlm_raw', [target_name, packet_name, item_name])
    var converted = this.decode_openc3_type(data)
    if (converted !== null) {
      data = converted
    }
    return data
  }
```

In the screen file I wanted to do something like this:
`BUTTON "Button" 'var value = api_raw.tlm("TARGET", "PACKET", "ITEM"); api.cmd("TARGET COMMAND with PARAM " + value)'`
What I had to do was:
`BUTTON "Button" 'var promise = api.tlm_raw("TARGET", "PACKET", "ITEM"); promise.then(value => api.cmd("TAGET COMMAND with PARAM " + value.toString() ))'`

It would be simpler if I could use the first way.

**Comment by jmthomas** [comment]
Yeah my existing solution didn't work. I'm still playing around with the best way to implement this. The promise option like you showed works but like you said it's a little awkward.
