### ISSUE TITLE
Add current page to browser tab title

### ISSUE THREAD

**Issue by tj-scherer** [OpenC3/openc3#91]
When using OpenC3 in the browser, every tab is titled "OpenC3".

![image](https://user-images.githubusercontent.com/68401889/186445055-1f5db0c9-d0ba-4ecd-a5fb-e4f9fdd9a7fa.png)

This makes it difficult to switch between tabs when there are too many tabs to be displayed side by side. It would be very convenient to include the page that is open, for example if you were using the Script Runner, that tab would be titled "OpenC3 - Script Runner" or something to that effect. Using the browser tools I changed the titles using the aforementioned format as well as just the name of the page. Looking at it , I prefer just using the name because it is easier to tell exactly what each tab is.

![image](https://user-images.githubusercontent.com/68401889/186445568-8be8d6de-21e3-4a91-aee0-9ef6a6d2d708.png)

**Comment by ryanmelt** [comment]
Good point.  We'll get this updated soon.
