### ISSUE TITLE
XTCE_converter output not accepted by NASA CCDD

### ISSUE THREAD

**Issue by smcHannah** [OpenC3/openc3#956]
Hi! I've followed the instructions in https://docs.openc3.com/docs/meta/xtce to convert my COSMOS configuration into an xtce file to import the definitions in NASA's CCDD software. However, when imported into CCDD no tables are produced.

**Environment (please complete the following information):**

- OS: Windows 11
- OpenC3 COSMOS Version: 5.12.0
- Browser: Chrome

**Comment by jmthomas** [comment]
I'm not familiar with NASA CCDD so I don't know what XTCE features may be missing. We do our best with the majority of XTCE elements but please let us know if there are key pieces that are missing. If you have a support contract you can reach out directly at support@openc3.com.

**Comment by ryanmelt** [comment]
I would suggest posting the XTCE to the CCDD guys, and maybe they an help identify what CCDD doesn't like about it.
https://github.com/nasa/CCDD
